import Header from './components/Header';
import { UserContextProvider } from './context/UserContext';
import './globals.css';

export const metadata = {
  title: 'Flight App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="bg-gray-100">
        <UserContextProvider>
          <Header />
          {children}
        </UserContextProvider>
      </body>
    </html>
  );
}
